0-2 fixed

diff --git a/basics_1/0-change_your_home_IP b/basics_1/0-change_your_home_IP
--- a/basics_1/0-change_your_home_IP
+++ b/basics_1/0-change_your_home_IP
@@ -1,14 +1,18 @@
 #!/usr/bin/env bash
+# Script that displays all active IPv4 IPs on the machine
 
-if [ "$(id -u)" -ne 0 ]; then
-    echo "This script must be run as root"
+# Using 'ip' command (modern approach)
+if command -v ip >/dev/null 2>&1; then
+    ip -4 addr show | grep -o 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | cut -d' ' -f2 | sort
+# Using 'ifconfig' as fallback (older systems)
+elif command -v ifconfig >/dev/null 2>&1; then
+    ifconfig | grep -o 'inet [0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | cut -d' ' -f2 | sort
+# Using hostname as a last resort
+elif command -v hostname >/dev/null 2>&1; then
+    hostname -I | tr ' ' '\n' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+
+ | sort
+else
+    echo "Error: No suitable tools found to retrieve IP addresses." >&2
     exit 1
 fi
 
-cp /etc/hosts /etc/hosts.bak
-
-sed -i '/\slocalhost$/d' /etc/hosts
-sed -i '/facebook\.com/d' /etc/hosts
-
-echo "127.0.0.2 localhost" >> /etc/hosts
-echo "8.8.8.8 facebook.com" >> /etc/hosts
